[workspace]
members = [
    "survey_cad",
    "survey_cad_cli",
    "bevy_pmetra",
    "survey_cad_gui",
    "slint_bevy_example",
    "cad_import", "pipe_network",
    "survey_cad_python",
    "survey_cad_slint_gui",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
