[package]
name = "survey_cad_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "survey_cad_python"
crate-type = ["cdylib", "rlib"]

[dependencies]
survey_cad = { path = "../survey_cad", default-features = false }
pyo3 = { version = "0.21", features = ["extension-module"] }
