[package]
name = "pipe_network"
edition.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
roxmltree = "0.20"

[dev-dependencies]
tempfile = "3.10"
