[package]
name = "survey_cad"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.15"
winit = "0.29"
log = "0.4"
env_logger = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
geojson = "0.24"
bevy = { version = "0.16", default-features = false }
