name: Build CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Install GDAL
        run: sudo apt-get update && sudo apt-get install -y libgdal-dev
      - name: Free disk space
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android $AGENT_TOOLSDIRECTORY
          df -h
      - name: Build survey_cad_cli
        run: cargo build -p survey_cad_cli --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: survey_cad_cli
          path: target/release/survey_cad_cli
