name: Release Windows Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
      - name: Install SQLite3
        run: choco install -y sqlite
      - name: Build CLI
        run: cargo build -p survey_cad_cli --release
      - name: Package Binary
        shell: bash
        run: |
          mkdir dist
          cp target/release/survey_cad_cli.exe dist/
          cd dist
          7z a survey_cad_cli-windows.zip survey_cad_cli.exe
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/survey_cad_cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
